[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/e/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/entities"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/overview"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/scenarios"
  to = "/index.html"
  status = 200
